apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fcg-platform
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  type: ClusterIP