apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

labels:
  - pairs:
      app.kubernetes.io/part-of: fcg-platform
      app.kubernetes.io/component: observability
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - servicemonitor-fcg.yaml

configMapGenerator:
  - name: fcg-overview-dashboard
    files:
      - grafana-dashboards/fcg-overview.json
    options:
      labels:
        grafana_dashboard: "1"
