apiVersion: v1
kind: ConfigMap

metadata:
  name: rabbitmq-config
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

data:
  RABBITMQ_DEFAULT_VHOST: "/"
  RABBITMQ_NODE_NAME: "rabbit@localhost"
