apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: fcg-platform
  labels:
    app: rabbitmq
    component: message-broker
    tier: infrastructure

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
