apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fcg-platform
  labels:
    app: rabbitmq
    component: message-broker
    tier: infrastructure

type: Opaque

data:
  RABBITMQ_DEFAULT_USER: ZmNn
  RABBITMQ_DEFAULT_PASS: ZmNnMTIz
  RABBITMQ_ERLANG_COOKIE: ZmNnLWNvb2tpZQ==
