apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: rabbitmq

  ports:
    - name: amqp
      port: 5672
      targetPort: amqp

    - name: management
      port: 15672
      targetPort: management
