apiVersion: v1
kind: Service

metadata:
  name: fcg-redis
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: fcg-redis
    app.kubernetes.io/instance: fcg-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: fcg-redis

  ports:
    - name: redis
      port: 6379
      targetPort: 6379