apiVersion: v1
kind: Secret

metadata:
  name: kong-secret
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: kong
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:
  JWT_SECRET: "FcgUsers_Secret_Key_2026_High_Security_Token"
