@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title FCG Platform - System Context

LAYOUT_LEFT_RIGHT()

Person(user, "Usuário", "Realiza cadastro, autenticação e compra de jogos.")

System_Ext(kong, "Kong API Gateway", "API Gateway\nRoteamento, autenticação JWT e rate limiting")

System_Boundary(fcg, "FCG Platform") {

    System(users, "Users", "Cadastro e autenticação")

    System(catalog, "Catalog", "Catálogo de jogos")

    System(payments, "Payments", "Processamento de pagamentos")

    System(notifications, "Notifications", "Envio de notificações")
}

System_Ext(rabbitmq, "RabbitMQ", "Broker de Mensagens")
System_Ext(postgres, "PostgreSQL", "Persistência dos dados")
System_Ext(email, "Serviço de E-mail", "Envio de notificações")


' ==================================================
' POSICIONAMENTO
' ==================================================

Lay_R(user, kong)

Lay_R(kong, users)
Lay_D(kong, catalog)

Lay_R(users, catalog)
Lay_R(catalog, payments)
Lay_R(payments, notifications)

Lay_D(catalog, rabbitmq)
Lay_D(rabbitmq, postgres)

Lay_R(notifications, email)


' ==================================================
' RELACIONAMENTOS EXTERNOS
' ==================================================

Rel(user, kong, "Requisições", "HTTPS")

Rel(kong, users, "Roteia requisições", "HTTP")
Rel(kong, catalog, "Roteia requisições", "HTTP")
Rel(kong, payments, "Roteia requisições", "HTTP")


' ==================================================
' COMUNICAÇÃO ASSÍNCRONA
' ==================================================

Rel(users, rabbitmq, "Publica eventos", "AMQP")
Rel(catalog, rabbitmq, "Publica eventos", "AMQP")
Rel(payments, rabbitmq, "Publica eventos", "AMQP")
Rel(notifications, rabbitmq, "Consome eventos", "AMQP")


' ==================================================
' PERSISTÊNCIA
' ==================================================

Rel(users, postgres, "Persiste dados", "SQL")
Rel(catalog, postgres, "Persiste dados", "SQL")
Rel(payments, postgres, "Persiste dados", "SQL")


' ==================================================
' NOTIFICAÇÕES
' ==================================================

Rel(notifications, email, "Envia e-mails", "SMTP/HTTP")

@enduml