apiVersion: v1
kind: Secret

metadata:
  name: pgadmin-secret
  namespace: fcg-platform

  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/component: database-admin
    app.kubernetes.io/part-of: fcg-platform
    app.kubernetes.io/managed-by: kubectl

type: Opaque

stringData:
  PGADMIN_DEFAULT_EMAIL: admin@fcg.com
  PGADMIN_DEFAULT_PASSWORD: admin123
